[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=nostr_relay --cov-report html -n auto"

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
target-version = "py311"

